### ISSUE TITLE
Object function has no method 'room' with code based on example

### ISSUE THREAD

**Issue by cbebry** [techpines/bone.io#19]
I put together an example to test out bone.io's pub/sub capabilities with the room functionality. I followed the example found on the website 'http://bone.io/#io/pub/sub'

I got the error below, stating that the object function does not have a method 'room'. It could be possible that I'm using it wrong, though I did base my test off the code from the site.

If you wish to see the code that triggers the error, I have it up in a repo and that specific file/line can be found here:

https://github.com/cbebry/quick-hapi-bone.io/blob/e81c720d2d15bc35633889aeb1e3e55c9a80c0d9/index.js#L45

The error:

```
/home/spectrum/quick-hapi-bone.io/index.js:45
                                this.room(data.room).broadcast({ message: data.message });
                                     ^
TypeError: Object function (socket) {
      return createIO(socket, options);
    } has no method 'room'
    at Function.bone.io.inbound.send (/home/spectrum/quick-hapi-bone.io/index.js:45:10)
    at /home/spectrum/quick-hapi-bone.io/node_modules/bone.io/lib/node/io.coffee:107:24
    at Object.async.eachSeries (/home/spectrum/quick-hapi-bone.io/node_modules/bone.io/node_modules/async/lib/async.js:127:20)
    at Socket.<anonymous> (/home/spectrum/quick-hapi-bone.io/node_modules/bone.io/lib/node/io.coffee:101:22)
    at Socket.EventEmitter.emit [as $emit] (events.js:95:17)
    at SocketNamespace.handlePacket (/home/spectrum/quick-hapi-bone.io/node_modules/socket.io/lib/namespace.js:335:22)
    at Manager.onClientMessage (/home/spectrum/quick-hapi-bone.io/node_modules/socket.io/lib/manager.js:488:38)
    at WebSocket.Transport.onMessage (/home/spectrum/quick-hapi-bone.io/node_modules/socket.io/lib/transport.js:387:20)
    at Parser.<anonymous> (/home/spectrum/quick-hapi-bone.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:39:10)
    at Parser.EventEmitter.emit (events.js:95:17)
    at finish (/home/spectrum/quick-hapi-bone.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:288:16)
    at Parser.expectHandler (/home/spectrum/quick-hapi-bone.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:299:15)
    at Parser.add (/home/spectrum/quick-hapi-bone.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:466:24)
    at Parser.expect (/home/spectrum/quick-hapi-bone.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:499:10)
    at Parser.<anonymous> (/home/spectrum/quick-hapi-bone.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:298:18)
    at Parser.add (/home/spectrum/quick-hapi-bone.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:466:24)
    at Parser.expect (/home/spectrum/quick-hapi-bone.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:499:10)
    at expectData (/home/spectrum/quick-hapi-bone.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:296:16)
    at Parser.opcodeHandlers.1 (/home/spectrum/quick-hapi-bone.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:313:9)
    at Parser.processPacket (/home/spectrum/quick-hapi-bone.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:533:8)
    at Parser.add (/home/spectrum/quick-hapi-bone.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:466:24)
    at Parser.expect (/home/spectrum/quick-hapi-bone.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:499:10)
    at Parser.endPacket (/home/spectrum/quick-hapi-bone.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:553:8)
    at finish (/home/spectrum/quick-hapi-bone.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:291:14)
    at Parser.<anonymous> (/home/spectrum/quick-hapi-bone.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:299:15)
    at Parser.add (/home/spectrum/quick-hapi-bone.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:466:24)
    at Parser.expect (/home/spectrum/quick-hapi-bone.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:499:10)
    at Parser.<anonymous> (/home/spectrum/quick-hapi-bone.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:298:18)
    at Parser.add (/home/spectrum/quick-hapi-bone.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:466:24)
    at Parser.expect (/home/spectrum/quick-hapi-bone.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:499:10)
    at expectData (/home/spectrum/quick-hapi-bone.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:296:16)
    at Parser.opcodeHandlers.1 (/home/spectrum/quick-hapi-bone.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:313:9)
    at Parser.processPacket (/home/spectrum/quick-hapi-bone.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:533:8)
    at Parser.add (/home/spectrum/quick-hapi-bone.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:466:24)
    at Socket.<anonymous> (/home/spectrum/quick-hapi-bone.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:141:17)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:720:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:392:10)
    at emitReadable (_stream_readable.js:388:5)
    at readableAddChunk (_stream_readable.js:150:9)
    at Socket.Readable.push (_stream_readable.js:113:10)
    at TCP.onread (net.js:511:21)

```

Thank you for your time

**Comment by techpines** [comment]
It looks like the docs are slightly ahead of the code.  We changed the API for how rooms worked before we released, and it looks like it's still the old way.  For now you can do this, `this(data.room).broadcast({ message: data.message });`.  Originally, we had it to where you didn't have to call `room`, but the object itself was callable.

I'll be releasing a new module to npm in the next day or so to fix this, and I'll post back here.

**Comment by techpines** [comment]
@cbebry Just, released a new version:

```
0.8.7
```

Which should have the updated code, please let me know if you run into any other issue.

**Comment by cbebry** [comment]
Updated and I'm now seeing that the room function works! Thanks a bunch.
